# Generated by Django 5.2.9 on 2026-03-07 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='external_user_id',
            field=models.CharField(default='', help_text='the external user id, such as wecom_userid, dingtalk_userid, feishu_userid', max_length=100, null=True, verbose_name='external_user_id'),
        ),
    ]
