# Generated by Django 5.2.9 on 2026-03-08 23:23

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseAuth',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('label', models.JSONField(blank=True, default=dict, verbose_name='label')),
                ('creator_id', models.UUIDField(default=uuid.uuid4, editable=False, null=True, verbose_name='creator_id')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated_at')),
                ('tenant_id', models.UUIDField(default='00000000-0000-0000-0000-000000000001', verbose_name='tenant_id')),
                ('type', models.CharField(choices=[('wecom', 'wecom'), ('microsoft_oidc', 'microsoft_oidc')], help_text='Authentication type', max_length=50, verbose_name='type')),
                ('is_enabled', models.BooleanField(default=False, verbose_name='is_enabled')),
                ('description', models.CharField(blank=True, default='', max_length=500, verbose_name='description')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MicrosoftOidcAuthConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('label', models.JSONField(blank=True, default=dict, verbose_name='label')),
                ('creator_id', models.UUIDField(default=uuid.uuid4, editable=False, null=True, verbose_name='creator_id')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated_at')),
                ('tenant_id', models.UUIDField(default='00000000-0000-0000-0000-000000000001', verbose_name='tenant_id')),
                ('client_id', models.CharField(default='', help_text='Application (client) ID', max_length=200, verbose_name='client_id')),
                ('client_secret', models.CharField(default='', help_text='Application Secret', max_length=500, verbose_name='client_secret')),
                ('redirect_uri', models.CharField(default='', help_text='Redirect URI', max_length=500, verbose_name='redirect_uri')),
                ('azure_tenant_id', models.CharField(default='', help_text='Directory (tenant) ID', max_length=200, verbose_name='azure_tenant_id')),
                ('base_auth', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='microsoft_oidc_config', to='manage.baseauth')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WecomAuthConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('label', models.JSONField(blank=True, default=dict, verbose_name='label')),
                ('creator_id', models.UUIDField(default=uuid.uuid4, editable=False, null=True, verbose_name='creator_id')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated_at')),
                ('tenant_id', models.UUIDField(default='00000000-0000-0000-0000-000000000001', verbose_name='tenant_id')),
                ('client_id', models.CharField(default='', help_text='Wecom Corp ID', max_length=200, verbose_name='client_id')),
                ('client_secret', models.CharField(default='', help_text='Wecom Corp Secret', max_length=500, verbose_name='client_secret')),
                ('redirect_uri', models.CharField(default='', max_length=500, verbose_name='redirect_uri')),
                ('agent_id', models.CharField(default='', help_text='Agent ID', max_length=100, verbose_name='agent_id')),
                ('base_auth', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='wecom_config', to='manage.baseauth')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
